
FROM us-docker.pkg.dev/cookies-eng/public/base/codespaces:v1j@sha256:c25dc111caad63e534affd0fd338d23a497bfc979c08dfe4a8e3e962d0f70281

ENV SHELL=zsh \
    HOME=/home/dev \
    DEVCONTAINER=yes

USER dev
WORKDIR /home/dev
